version: '3'

services:
  neo4j:
    image: neo4j:latest
    volumes:
      # - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_heap_maxSize=1G
      - NEO4J_AUTH=neo4j/FengTu
  
  nestjs:
    image: node:${NODE_VERSION}
    working_dir: /usr/src/server
    volumes:
      - ./server:/usr/src/server
    command: npm config set registry https://registry.npm.taobao.org
    # For production
    command: npm run build admin
    command: node dist/apps/admin/main.js
    # For development 
    # command: npm run start admin    
    restart: always
    ports:
      - 3000:3000
  
  vue:    
    image: node:${NODE_VERSION}
    working_dir: /usr/src/admin
    command: npm config set registry https://registry.npm.taobao.org
    # For production
    command: npm run build
    restart: on-failure
    # For development 
    # command: npm run serve
    # restart: always
    volumes:
      - ./admin:/usr/src/admin
    environment:
      - SERVICE_NAME=vue    
    expose:
      - "80"
    ports:
      - "8080:8080"
  
  nginx:
    build: ./admin
    ports:
      - "8081:8080"