export const TENCENTCLOUD_CONFIG: string = 'TENCENTCLOUD_CONFIG'
export const TENCENTCLOUD_CLIENT: string = 'TENCENTCLOUD_CLIENT'
export const TENCENTCLOUD_TMT_CLIENT: string = 'TENCENTCLOUD_TMT_CLIENT'